UPDATE bancos SET icono = 'do-banco-bhd-official.png' WHERE pais_id = 1 AND nombre = 'Banco BHD';
UPDATE bancos SET icono = 'do-banco-ademi-official.png' WHERE pais_id = 1 AND nombre = 'Banco Ademi';
UPDATE bancos SET icono = 'do-banreservas-official.png' WHERE pais_id = 1 AND nombre = 'Banreservas';
UPDATE bancos SET icono = 'do-banco-santa-cruz-official.svg' WHERE pais_id = 1 AND nombre = 'Banco Santa Cruz';
UPDATE bancos SET icono = 'do-bancamerica.svg' WHERE pais_id = 1 AND nombre = 'Bancamerica';
UPDATE bancos SET icono = 'do-banco-activo-official.png' WHERE pais_id = 1 AND nombre = 'Banco Activo Dominicana';
UPDATE bancos SET icono = 'do-banco-bdi-official.svg' WHERE pais_id = 1 AND nombre = 'Banco BDI';
UPDATE bancos SET icono = 'https://www.bancocaribe.com.do/logo.png' WHERE pais_id = 1 AND nombre = 'Banco Caribe';
UPDATE bancos SET icono = 'do-banco-del-progreso.svg' WHERE pais_id = 1 AND nombre = 'Banco del Progreso';
UPDATE bancos SET icono = 'do-banco-lafise-official.svg' WHERE pais_id = 1 AND nombre = 'Banco Lafise';
UPDATE bancos SET icono = 'do-banco-lopez-de-haro-official.png' WHERE pais_id = 1 AND nombre = 'Banco Lopez de Haro';
UPDATE bancos SET icono = 'https://popularenlinea.com/_catalogs/masterpage/popularenlinea/shared/images/BPD-logo.png' WHERE pais_id = 1 AND nombre = 'Banco Popular Dominicano';
UPDATE bancos SET icono = 'do-banco-promerica-official.webp' WHERE pais_id = 1 AND nombre = 'Banco Promerica';
UPDATE bancos SET icono = 'do-banco-vimenca-official.svg' WHERE pais_id = 1 AND nombre = 'Banco Vimenca';
UPDATE bancos SET icono = 'do-banesco-official.svg' WHERE pais_id = 1 AND nombre = 'Banesco';
UPDATE bancos SET icono = 'do-bellbank.svg' WHERE pais_id = 1 AND nombre = 'BellBank';
UPDATE bancos SET icono = 'do-citibank.svg' WHERE pais_id = 1 AND nombre = 'Citibank';
UPDATE bancos SET icono = 'do-scotiabank-official.svg' WHERE pais_id = 1 AND nombre = 'Scotiabank';
UPDATE bancos SET icono = 'do-asociacion-bonao-official.png' WHERE pais_id = 1 AND nombre = 'Asociacion Bonao de Ahorros y Prestamos';
UPDATE bancos SET icono = 'do-asociacion-cibao-official.png' WHERE pais_id = 1 AND nombre = 'Asociacion Cibao de Ahorros y Prestamos';
UPDATE bancos SET icono = 'https://adap.com.do/wp-content/themes/asocdu/images/logoasociacionduarteblanco.png' WHERE pais_id = 1 AND nombre = 'Asociacion Duarte de Ahorros y Prestamos';
UPDATE bancos SET icono = 'do-asociacion-la-nacional-official.svg' WHERE pais_id = 1 AND nombre = 'Asociacion La Nacional de Ahorros y Prestamos';
UPDATE bancos SET icono = 'do-asociacion-la-vega-real-official.jpg' WHERE pais_id = 1 AND nombre = 'Asociacion La Vega Real de Ahorros y Prestamos';
UPDATE bancos SET icono = 'do-asociacion-maguana.svg' WHERE pais_id = 1 AND nombre = 'Asociacion Maguana de Ahorros y Prestamos';
UPDATE bancos SET icono = 'do-asociacion-mocana.svg' WHERE pais_id = 1 AND nombre = 'Asociacion Mocana de Ahorros y Prestamos';
UPDATE bancos SET icono = 'https://asociacionperavia.com.do/wp-content/themes/peravia/images/logo.png' WHERE pais_id = 1 AND nombre = 'Asociacion Peravia de Ahorros y Prestamos';
UPDATE bancos SET icono = 'do-asociacion-popular-official.png' WHERE pais_id = 1 AND nombre = 'Asociacion Popular de Ahorros y Prestamos';
UPDATE bancos SET icono = 'do-asociacion-romana-official.png' WHERE pais_id = 1 AND nombre = 'Asociacion Romana de Ahorros y Prestamos';
