UPDATE bancos SET icono = 'do-banco-bhd.svg' WHERE pais_id = 1 AND nombre = 'Banco BHD';
UPDATE bancos SET icono = 'do-banco-ademi.svg' WHERE pais_id = 1 AND nombre = 'Banco Ademi';
UPDATE bancos SET icono = 'do-banreservas.svg' WHERE pais_id = 1 AND nombre = 'Banreservas';
UPDATE bancos SET icono = 'do-banco-santa-cruz.svg' WHERE pais_id = 1 AND nombre = 'Banco Santa Cruz';
UPDATE bancos SET icono = 'do-bancamerica.svg' WHERE pais_id = 1 AND nombre = 'Bancamerica';
UPDATE bancos SET icono = 'do-banco-activo.svg' WHERE pais_id = 1 AND nombre = 'Banco Activo Dominicana';
UPDATE bancos SET icono = 'do-banco-bdi.svg' WHERE pais_id = 1 AND nombre = 'Banco BDI';
UPDATE bancos SET icono = 'do-banco-caribe.svg' WHERE pais_id = 1 AND nombre = 'Banco Caribe';
UPDATE bancos SET icono = 'do-banco-del-progreso.svg' WHERE pais_id = 1 AND nombre = 'Banco del Progreso';
UPDATE bancos SET icono = 'do-banco-lafise.svg' WHERE pais_id = 1 AND nombre = 'Banco Lafise';
UPDATE bancos SET icono = 'do-banco-lopez-de-haro.svg' WHERE pais_id = 1 AND nombre = 'Banco Lopez de Haro';
UPDATE bancos SET icono = 'do-banco-popular-dominicano.svg' WHERE pais_id = 1 AND nombre = 'Banco Popular Dominicano';
UPDATE bancos SET icono = 'do-banco-promerica.svg' WHERE pais_id = 1 AND nombre = 'Banco Promerica';
UPDATE bancos SET icono = 'do-banco-vimenca.svg' WHERE pais_id = 1 AND nombre = 'Banco Vimenca';
UPDATE bancos SET icono = 'do-banesco.svg' WHERE pais_id = 1 AND nombre = 'Banesco';
UPDATE bancos SET icono = 'do-bellbank.svg' WHERE pais_id = 1 AND nombre = 'BellBank';
UPDATE bancos SET icono = 'do-citibank.svg' WHERE pais_id = 1 AND nombre = 'Citibank';
UPDATE bancos SET icono = 'do-scotiabank.svg' WHERE pais_id = 1 AND nombre = 'Scotiabank';
UPDATE bancos SET icono = 'do-asociacion-bonao.svg' WHERE pais_id = 1 AND nombre = 'Asociacion Bonao de Ahorros y Prestamos';
UPDATE bancos SET icono = 'do-asociacion-cibao.svg' WHERE pais_id = 1 AND nombre = 'Asociacion Cibao de Ahorros y Prestamos';
UPDATE bancos SET icono = 'do-asociacion-duarte.svg' WHERE pais_id = 1 AND nombre = 'Asociacion Duarte de Ahorros y Prestamos';
UPDATE bancos SET icono = 'do-asociacion-la-nacional.svg' WHERE pais_id = 1 AND nombre = 'Asociacion La Nacional de Ahorros y Prestamos';
UPDATE bancos SET icono = 'do-asociacion-la-vega-real.svg' WHERE pais_id = 1 AND nombre = 'Asociacion La Vega Real de Ahorros y Prestamos';
UPDATE bancos SET icono = 'do-asociacion-maguana.svg' WHERE pais_id = 1 AND nombre = 'Asociacion Maguana de Ahorros y Prestamos';
UPDATE bancos SET icono = 'do-asociacion-mocana.svg' WHERE pais_id = 1 AND nombre = 'Asociacion Mocana de Ahorros y Prestamos';
UPDATE bancos SET icono = 'do-asociacion-peravia.svg' WHERE pais_id = 1 AND nombre = 'Asociacion Peravia de Ahorros y Prestamos';
UPDATE bancos SET icono = 'do-asociacion-popular.svg' WHERE pais_id = 1 AND nombre = 'Asociacion Popular de Ahorros y Prestamos';
UPDATE bancos SET icono = 'do-asociacion-romana.svg' WHERE pais_id = 1 AND nombre = 'Asociacion Romana de Ahorros y Prestamos';
